/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_weight_scale                   19
#define gattdb_weight_measurement_1           21
#define gattdb_weight_measurement_2           23
#define gattdb_weight_measurement_3           25
#define gattdb_weight_measurement_4           27
#define gattdb_weight_measurement_5           29
#define gattdb_weight_measurement_6           31
#define gattdb_weight_measurement_7           33
#define gattdb_weight_measurement_8           35
#define gattdb_weight_measurement_9           37
#define gattdb_weight_measurement_10          39
#define gattdb_team1_count                    42
#define gattdb_team2_count                    45
#define gattdb_ota                            47
#define gattdb_ota_control                    49


#endif // __GATT_DB_H
